openapi: 3.0.3

info:
  title: Patient management API-REST
  version: 1.0.0
  description: API-REST developed with Node.js and Express

paths:
  /pacientes:
    get:
      summary: Get all the patients
      description: Returns an array containing all patients stored in the database

      responses:
        "200":
          description: Array of patients retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Paciente"

        "401":
          description: error en el token

        "500":
          description: Internal Server Error

    get/id:
      summary: Get a patient by his id
      description: Returns an array containing only the patient who belongs the id

      responses:
        "200":
          description: Array of patient retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Paciente"

        "404":
          description: Paciente no encontrado

        "401":
          description: error en el token

        "500":
          description: Internal Server Error

    post:
      summary: Create a new patient
      description: Insert a new patient into the patients table in the database

      responses:
        "201":
          description: Paciente insertado correctamente

        "400":
          description: Datos invalidos

        "401":
          description: Error en el token

    put:
      summary: Update an existent patient
      description: Update an existent patient data into the database by his id

      responses:
        "200":
          description: Paciente actualizado correctamente

        "404":
          description: Paciente no encontrado

        "400":
          description: Datos invalidos

        "401":
          description: Error en el token

    delete:
      summary: Delete a patient
      description: Delete a patient from the database by his id

      responses:
        "204":
          description: Paciente eliminado correctamente

        "404":
          description: Paciente no encontrado

        "401":
          description: Error en el token

  /citas:
    get:
      summary: Get all the citas
      description: Return an array of all citas stored in the database

      responses:
        "200":
          description: Lista de citas obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cita"

        "401":
          description: Error en el token

    get/id:
      summary: get a cita by id
      description: Return an array with a cita by id

      responses:
        "200":
          description: Cita obtenida correctamente
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cita"

        "404":
          description: "Cita no encontrada"

        "401":
          description: "Error en el token"

    post:
      summary: Insertar cita
      description: Insertar una nueva cita en la base de Datos

      responses:
        "201":
          description: Cita insertada correctamente

        "400":
          description: Campos obligatorios vacios

        "401":
          description: Error en el token

    put:
      summary: Actualizar cita
      description: Actualizar una cita existente en la base de datos por su id

      responses:
        "200":
          description: Cita actualizada correctamente

        "404":
          description: Cita no encontrada

        "400":
          description: Datos invalidos

        "401":
          description: Error en el token

    delete:
      summary: Eliminar cita
      description: Eliminar una cita existente en la base de datos por su id

      responses:
        "204":
          description: Cita eliminada correctamente

        "404":
          description: Cita no encontrada

        "401":
          description: Error en el token

  /usuarios:
    get:
      summary: Obtener todos los usuarios
      description: Obtiene un array con todos los usuarios registrados en la base de datos

      responses:
        "200":
          description: Usuarios obtenidos correctamente
          content:
            application/json:
              schema:
                type: array
                items: "#/components/schemas/Usuario"

    get/id:
    post:
    put:
    delete:

components:
  schemas:
    Paciente:
      type: object
      required:
        - PacienteId
      properties:
        PacienteId:
          type: integer
        DNI:
          type: string
        Nombre:
          type: string
        Direccion:
          type: string
        CodigoPostal:
          type: string
        Telefono:
          type: string
        Genero:
          type: string
        FechaNacimiento:
          type: string
          format: date
        Correo:
          type: string

    Cita:
      type: object
      required:
        - CitaId
      properties:
        CitaId:
          type: integer
        PacienteId:
          type: string
        Fecha:
          type: string
          format: date
        HoraInicio:
          type: string
        HoraFin:
          type: string
        Estado:
          type: string
        Motivo:
          type: string

    Usuario:
      type: object
      required:
        - UsuarioId
        - Usuario
        - Password
        - Estado
        - Rol
      properties:
        UsuarioId:
          type: integer
        Usuario:
          type: string
        Password:
          type: string
        Estado:
          type: string
        Rol:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
